// <auto-generated />
using System;
using AI_Readiness_Hub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI_Readiness_Hub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605055806_OptimizeDashboardWorkspacePerformance")]
    partial class OptimizeDashboardWorkspacePerformance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIAnalysisOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InputSummary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutputContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "AnalysisType", "VersionNumber");

                    b.ToTable("AIAnalysisOutputs");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIRoadmapItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dependencies")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedOutcome")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("RelatedUseCaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.HasIndex("RelatedUseCaseId");

                    b.ToTable("AIRoadmapItems");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIUseCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessProblem")
                        .HasColumnType("text");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedBenefit")
                        .HasColumnType("text");

                    b.Property<string>("ImplementationComplexity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequiredData")
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TimeToValue")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("AIUseCases");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIUseCaseScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AIUseCaseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataReadinessScore")
                        .HasColumnType("integer");

                    b.Property<int>("FeasibilityScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriorityScore")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<int>("RiskSafetyScore")
                        .HasColumnType("integer");

                    b.Property<int>("RoiScore")
                        .HasColumnType("integer");

                    b.Property<string>("ScoringComment")
                        .HasColumnType("text");

                    b.Property<int>("StrategicFitScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AIUseCaseId")
                        .IsUnique();

                    b.ToTable("AIUseCaseScores");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AssessmentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text");

                    b.Property<string>("AnswerType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("AssessmentResponseId")
                        .HasColumnType("integer");

                    b.Property<string>("CompletenessStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReadinessAssessmentId")
                        .HasColumnType("integer");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentResponseId");

                    b.HasIndex("ReadinessAssessmentId");

                    b.ToTable("AssessmentAnswers");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AssessmentResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerCount")
                        .HasColumnType("integer");

                    b.Property<string>("ClientToken")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalResponseId")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("text");

                    b.Property<int>("ReadinessAssessmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseLabel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ResponseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalResponseId");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("ReadinessAssessmentId", "ExternalResponseId");

                    b.HasIndex("ReadinessAssessmentId", "ReceivedAt");

                    b.HasIndex("ReadinessAssessmentId", "ResponseNumber")
                        .IsUnique();

                    b.HasIndex("Status", "ReceivedAt");

                    b.ToTable("AssessmentResponses");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "CreatedAt");

                    b.ToTable("ClientActivityLogs");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedConsultant")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("BusinessModel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("CompanySizeRange")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ConsultingPackage")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContactPersonEmail")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContactPersonPhone")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Industry")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("KeyRisksSummary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NextAction")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<decimal?>("OverallReadinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Region")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("RevenueRange")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("CurrentStage");

                    b.HasIndex("LastModifiedAt");

                    b.ToTable("ClientCompanies");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiSummary")
                        .HasColumnType("text");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KeyInsights")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("UsedInReport")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "UploadedAt");

                    b.ToTable("ClientDocuments");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalReportContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "ReportStatus");

                    b.HasIndex("ClientCompanyId", "VersionNumber");

                    b.HasIndex("ReportStatus", "GeneratedAt");

                    b.ToTable("ClientReports");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "Status");

                    b.HasIndex("Status", "DueDate");

                    b.ToTable("ClientTasks");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientWorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "DisplayOrder");

                    b.ToTable("ClientWorkflowSteps");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.CompetitorInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiUseCasesObserved")
                        .HasColumnType("text");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("CompetitorName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsightText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceNotes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("StrengthComparedToClient")
                        .HasColumnType("text");

                    b.Property<string>("WeaknessComparedToClient")
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("CompetitorInsights");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ConsultantNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoteTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "CreatedAt");

                    b.ToTable("ConsultantNotes");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.GapAnalysisItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GapArea")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Impact")
                        .HasColumnType("text");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SuggestedAction")
                        .HasColumnType("text");

                    b.Property<string>("SuggestedFollowUpQuestion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "Status");

                    b.ToTable("GapAnalysisItems");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.IndustryInsight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsightText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Relevance")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("IndustryInsights");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.MeetingTranscript", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FollowUpQuestions")
                        .HasColumnType("text");

                    b.Property<string>("KeyDecisions")
                        .HasColumnType("text");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TranscriptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "SessionDate");

                    b.ToTable("MeetingTranscripts");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReadinessAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientToken")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomFormUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ExternalResponseId")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FormStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FormUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GeneratedFormUrl")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastReminderSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResponseReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentToEmail")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientToken");

                    b.HasIndex("ExternalResponseId");

                    b.HasIndex("ClientCompanyId", "CreatedAt");

                    b.HasIndex("FormStatus", "SentAt");

                    b.ToTable("ReadinessAssessments");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReadinessFormSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientReferenceEntryId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultFormUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EmailBodyTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ReadinessFormSettings");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReadinessScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessClarityScore")
                        .HasColumnType("integer");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataReadinessScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("PeopleGovernanceScore")
                        .HasColumnType("integer");

                    b.Property<int>("ProcessReadinessScore")
                        .HasColumnType("integer");

                    b.Property<string>("ScoreCategory")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ScoringSummary")
                        .HasColumnType("text");

                    b.Property<int>("TechnologyReadinessScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId", "CreatedAt");

                    b.ToTable("ReadinessScores");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReportSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientReportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SectionContent")
                        .HasColumnType("text");

                    b.Property<int>("SectionOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SectionStatus")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SectionTitle")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("ClientReportId");

                    b.ToTable("ReportSections");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.SwotAnalysisItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ClientCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("ConsultantComment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceSource")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClientCompanyId");

                    b.ToTable("SwotAnalysisItems");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIAnalysisOutput", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("AnalysisOutputs")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIRoadmapItem", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("RoadmapItems")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI_Readiness_Hub.Models.AIUseCase", "RelatedUseCase")
                        .WithMany()
                        .HasForeignKey("RelatedUseCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientCompany");

                    b.Navigation("RelatedUseCase");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIUseCase", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("UseCases")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIUseCaseScore", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.AIUseCase", "AIUseCase")
                        .WithOne("Score")
                        .HasForeignKey("AI_Readiness_Hub.Models.AIUseCaseScore", "AIUseCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIUseCase");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AssessmentAnswer", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.AssessmentResponse", "AssessmentResponse")
                        .WithMany("Answers")
                        .HasForeignKey("AssessmentResponseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AI_Readiness_Hub.Models.ReadinessAssessment", "ReadinessAssessment")
                        .WithMany("Answers")
                        .HasForeignKey("ReadinessAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentResponse");

                    b.Navigation("ReadinessAssessment");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AssessmentResponse", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ReadinessAssessment", "ReadinessAssessment")
                        .WithMany("Responses")
                        .HasForeignKey("ReadinessAssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadinessAssessment");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientActivityLog", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientDocument", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("Documents")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientReport", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("Reports")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientTask", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("Tasks")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientWorkflowStep", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("WorkflowSteps")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.CompetitorInsight", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("CompetitorInsights")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ConsultantNote", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("Notes")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.GapAnalysisItem", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("GapAnalysisItems")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.IndustryInsight", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("IndustryInsights")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.MeetingTranscript", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("MeetingTranscripts")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReadinessAssessment", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("ReadinessAssessments")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReadinessScore", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("ReadinessScores")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReportSection", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientReport", "ClientReport")
                        .WithMany("Sections")
                        .HasForeignKey("ClientReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientReport");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.SwotAnalysisItem", b =>
                {
                    b.HasOne("AI_Readiness_Hub.Models.ClientCompany", "ClientCompany")
                        .WithMany("SwotItems")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AIUseCase", b =>
                {
                    b.Navigation("Score");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.AssessmentResponse", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientCompany", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("AnalysisOutputs");

                    b.Navigation("CompetitorInsights");

                    b.Navigation("Documents");

                    b.Navigation("GapAnalysisItems");

                    b.Navigation("IndustryInsights");

                    b.Navigation("MeetingTranscripts");

                    b.Navigation("Notes");

                    b.Navigation("ReadinessAssessments");

                    b.Navigation("ReadinessScores");

                    b.Navigation("Reports");

                    b.Navigation("RoadmapItems");

                    b.Navigation("SwotItems");

                    b.Navigation("Tasks");

                    b.Navigation("UseCases");

                    b.Navigation("WorkflowSteps");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ClientReport", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("AI_Readiness_Hub.Models.ReadinessAssessment", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
